[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to the Next.js app
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler/:splat"
  status = 200
